name: CI

# Run manually only
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build
        id: build
        run: | 
          echo Doing some build here
          chmod +x ./randomaction.sh && ./randomaction.sh
      - name: Doing some tests here
        id: tests
        run: |
          echo Doing some tests here
          ./randomaction.sh
      - name: Doing some publish here
        id: publish
        run: |
          echo Doing some publish here
          ./randomaction.sh
      - name: Doing some deploy here
        id: deploy
        run: |
          echo Doing some deploy here
          ./randomaction.sh
      - name: Notifications
        if: failure()
        env:
          PAGERDUTY_TOKEN: ${{ secrets.PAGERDUTY_TOKEN }}
        run: |
          curl -X POST --header 'Content-Type: application/json' \
            --header 'Accept: application/vnd.pagerduty+json;version=2' \
            --header 'From: <veron.blg@gmail.com>' \
            --header "Authorization: Token token=${{ secrets.PAGERDUTY_TOKEN }}" \
            -d '{"incident": {"type": "incident", "title": "Build failed", "service": {"id": "${{ secrets.PAGERDUTY_SERVICE }}", "type": "service_reference"} } }' \
            https://api.pagerduty.com/incidents